name: Build and Push Docker Image

on:
  push:
    branches:
      - main # atau 'master', tergantung default branch kamu

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.alfianndi }}
          password: ${{ secrets.dckr_pat_9GA_6HJNiZEEj1rd6WCFRtdGjG8 }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.alfianndi }}/anomali:latest
